query MyQuery($filter: bookmarks_bool_exp!) {
  bookmarks(where: $filter) {
    recipe{
      created_at
    description
    preparation_time
    recipe_id
    title
    likes_aggregate {
      aggregate {
        count
      }
    }
    reviews_aggregate {
      aggregate {
        avg {
          rating
        }
        count
      }
    }
    recipe_images {
      image
      id
    }
    stepes {
      id
      order
      step_description
    }
    user {
      first_name
      id
      recipes_aggregate {
        aggregate {
          count
        }
      }
    }
    }
  }
}
