query searchCatagory(
  $filter: categories_bool_exp,
  $orderd_by: [categories_order_by!],
  $limit: Int,
  $offset: Int
) {
  categories(
    where: $filter,
    order_by: $orderd_by,
    limit: $limit
    offset: $offset
  ) {
    category_id
    name
  }
}
